"""empty message

Revision ID: 70141b97d0fc
Revises: 80d10dcdb8cc
Create Date: 2020-06-22 19:34:14.375484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70141b97d0fc'
down_revision = '80d10dcdb8cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_following_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendships')
    # ### end Alembic commands ###
