"""empty message

Revision ID: c7835814fbe9
Revises: f002841a2add
Create Date: 2020-06-18 19:21:02.051185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7835814fbe9'
down_revision = 'f002841a2add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio',
               existing_type=mysql.VARCHAR(length=280),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('users', 'bio',
               existing_type=mysql.VARCHAR(length=280),
               nullable=False)
    # ### end Alembic commands ###
