"""empty message

Revision ID: fd3feae6bba5
Revises: 70141b97d0fc
Create Date: 2020-06-23 11:33:20.745277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3feae6bba5'
down_revision = '70141b97d0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followtable',
    sa.Column('source_user_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.UniqueConstraint('source_user_id', 'target_user_id', name='unique_friendships')
    )
    op.create_index(op.f('ix_followtable_source_user_id'), 'followtable', ['source_user_id'], unique=False)
    op.create_index(op.f('ix_followtable_target_user_id'), 'followtable', ['target_user_id'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_following_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendships')
    op.drop_index(op.f('ix_followtable_target_user_id'), table_name='followtable')
    op.drop_index(op.f('ix_followtable_source_user_id'), table_name='followtable')
    op.drop_table('followtable')
    # ### end Alembic commands ###
